apiVersion: v1
data:
  "csi-migration": "false"
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- include "controller.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
