apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- include "controller.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
stringData:
  csi-vsphere.conf: |
    {{- .Values.controller.config | nindent 4 }}
