{{- range $roleName, $value := .Values.rbacMap.roles }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $roleName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
rules:
  {{- toYaml $value.rules | trim | nindent 2 }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $roleName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
subjects:
  {{- toYaml $value.subjects | trim | nindent 2 }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}