apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
  annotations:
    {{- include "controller.annotations" . | nindent 4 }}
stringData:
  vsphere.conf: |
    {{- toYaml .Values.config | trim | nindent 4 }}
