{{- if .Values.persistence.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
{{- if eq "nfs" .Values.persistence.pv.type }}
  nfs:
    server: {{ .Values.persistence.pv.nfs.server | quote }}
    path: {{ .Values.persistence.pv.nfs.path | quote }}
{{- else if eq "hostPath" .Values.persistence.pv.type }}
  hostPath:
    path: {{ .Values.persistence.pv.hostPath.path | quote }}
{{- end }}
{{- end }}
