{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- if (.Values.persistence.pv.enabled) }}
  storageClassName: ""
  volumeName: {{ include "app.fullname" . }}
{{- else if (.Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
{{- end }}
