apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
type: Opaque
data:
  admin: {{ .Values.telegram.admin | b64enc | quote }}
  token: {{ .Values.telegram.token | b64enc | quote }}
