{{- range $key, $value := .Values.storageClassMap }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $key }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
{{- toYaml $value | trim | nindent 0 }}
{{- end }}
