{{- range $key, $value := .Values.middlewareMap }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $key }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
spec:
  {{- toYaml $value.spec | trim | nindent 2 }}
{{- end }}
